{
 "title": "Jokes Application Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "External calls duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "external_api_chucknorris_call_duration_seconds_count"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "external_api_chucknorris_call_failures_total"
    }
   ]
  },
  {
   "title": "Total calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "external_api_chucknorris_calls_total"
    }
   ]
  }
 ]
}